version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.2.0
jobs:
  generate-config:
    executor: continuation/default
    steps:
      - checkout
      - run: 
          name: Generate Pipeline generated_config.yml file
          command: |
            ./scripts/generate-config "large" 2
      - continuation/continue:
          parameters: '{}'
          configuration_path: configs/generated_config.yml
workflows:
  setup-workflow:
    jobs:
      - generate-config
